# Generated by Django 4.2.19 on 2025-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='claps',
            field=models.CharField(blank=True, null=True),
        ),
    ]
