# Generated by Django 4.2.19 on 2025-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_claps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='claps',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
