# Generated by Django 4.2.19 on 2025-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
